//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokebot {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pokebot.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while calling the Github API..
        /// </summary>
        internal static string API_GithubError {
            get {
                return ResourceManager.GetString("API_GithubError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokebot.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A save state already exists for this bot. Do you want to use it ?.
        /// </summary>
        internal static string Bot_FileExistReplaceMessage {
            get {
                return ResourceManager.GetString("Bot_FileExistReplaceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already exists.
        /// </summary>
        internal static string Bot_FileExistReplaceTitle {
            get {
                return ResourceManager.GetString("Bot_FileExistReplaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot is not running.
        /// </summary>
        internal static string Bot_NotRunning {
            get {
                return ResourceManager.GetString("Bot_NotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot is running....
        /// </summary>
        internal static string Bot_Running {
            get {
                return ResourceManager.GetString("Bot_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot type is not supported.
        /// </summary>
        internal static string BotFactory_NotSupported {
            get {
                return ResourceManager.GetString("BotFactory_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This frame has already passed. Save the game and reload it (without save state)..
        /// </summary>
        internal static string BotPokeFinder_InvalidFrame {
            get {
                return ResourceManager.GetString("BotPokeFinder_InvalidFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot is unable to start because the save state doesn&apos;t exists anymore..
        /// </summary>
        internal static string BotPokeFinder_InvalidSaveState {
            get {
                return ResourceManager.GetString("BotPokeFinder_InvalidSaveState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All frames has been tested and the pokemon with PID {0} has not been found..
        /// </summary>
        internal static string BotPokeFinder_PokemonNotFound {
            get {
                return ResourceManager.GetString("BotPokeFinder_PokemonNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TID : {0} - SID : {1}.
        /// </summary>
        internal static string BotPokeFinder_TrainerInfo {
            get {
                return ResourceManager.GetString("BotPokeFinder_TrainerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot is unable to start because the save state doesn&apos;t exists anymore..
        /// </summary>
        internal static string BotStarter_InvalidSaveState {
            get {
                return ResourceManager.GetString("BotStarter_InvalidSaveState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This bot cannot be used because the party is not empty..
        /// </summary>
        internal static string BotStarter_PartyNotEmpty {
            get {
                return ResourceManager.GetString("BotStarter_PartyNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot is unable to start because the player is not in front of starters..
        /// </summary>
        internal static string BotStarter_WrongStartPosition {
            get {
                return ResourceManager.GetString("BotStarter_WrongStartPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ability.
        /// </summary>
        internal static string Discord_Ability {
            get {
                return ResourceManager.GetString("Discord_Ability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bot stopped because a pokemon with your filters has been encountered ! :partying_face:.
        /// </summary>
        internal static string Discord_Content {
            get {
                return ResourceManager.GetString("Discord_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey {0} ! {1}.
        /// </summary>
        internal static string Discord_ContentWithUser {
            get {
                return ResourceManager.GetString("Discord_ContentWithUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string Discord_Item {
            get {
                return ResourceManager.GetString("Discord_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IV Attack.
        /// </summary>
        internal static string Discord_IVAttack {
            get {
                return ResourceManager.GetString("Discord_IVAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IV Defense.
        /// </summary>
        internal static string Discord_IVDefense {
            get {
                return ResourceManager.GetString("Discord_IVDefense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IV Hp.
        /// </summary>
        internal static string Discord_IVHp {
            get {
                return ResourceManager.GetString("Discord_IVHp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IV Sp. Attack.
        /// </summary>
        internal static string Discord_IVSpAttack {
            get {
                return ResourceManager.GetString("Discord_IVSpAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IV Sp. Defense.
        /// </summary>
        internal static string Discord_IVSpDefense {
            get {
                return ResourceManager.GetString("Discord_IVSpDefense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IV Speed.
        /// </summary>
        internal static string Discord_IVSpeed {
            get {
                return ResourceManager.GetString("Discord_IVSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nature.
        /// </summary>
        internal static string Discord_Nature {
            get {
                return ResourceManager.GetString("Discord_Nature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        internal static string Discord_PokemonName {
            get {
                return ResourceManager.GetString("Discord_PokemonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shiny.
        /// </summary>
        internal static string Discord_Shiny {
            get {
                return ResourceManager.GetString("Discord_Shiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No :x:.
        /// </summary>
        internal static string Discord_ShinyNo {
            get {
                return ResourceManager.GetString("Discord_ShinyNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes :white_check_mark:.
        /// </summary>
        internal static string Discord_ShinyYes {
            get {
                return ResourceManager.GetString("Discord_ShinyYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainer.
        /// </summary>
        internal static string Discord_Trainer {
            get {
                return ResourceManager.GetString("Discord_Trainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send discord webhook: {0}.
        /// </summary>
        internal static string DiscordWebhook_Failed {
            get {
                return ResourceManager.GetString("DiscordWebhook_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while reading bot type..
        /// </summary>
        internal static string Error_ReadingBotType {
            get {
                return ResourceManager.GetString("Error_ReadingBotType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any gender.
        /// </summary>
        internal static string Filter_AnyGender {
            get {
                return ResourceManager.GetString("Filter_AnyGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any item.
        /// </summary>
        internal static string Filter_AnyItem {
            get {
                return ResourceManager.GetString("Filter_AnyItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any nature.
        /// </summary>
        internal static string Filter_AnyNature {
            get {
                return ResourceManager.GetString("Filter_AnyNature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any pokemon.
        /// </summary>
        internal static string Filter_AnyPokemon {
            get {
                return ResourceManager.GetString("Filter_AnyPokemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any type.
        /// </summary>
        internal static string Filter_AnyType {
            get {
                return ResourceManager.GetString("Filter_AnyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string Gender_Female {
            get {
                return ResourceManager.GetString("Gender_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genderless.
        /// </summary>
        internal static string Gender_Genderless {
            get {
                return ResourceManager.GetString("Gender_Genderless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string Gender_Male {
            get {
                return ResourceManager.GetString("Gender_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknow.
        /// </summary>
        internal static string Gender_Unknow {
            get {
                return ResourceManager.GetString("Gender_Unknow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The registered item cannot be used.
        /// </summary>
        internal static string InvalidRegisteredItem {
            get {
                return ResourceManager.GetString("InvalidRegisteredItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing.
        /// </summary>
        internal static string Item_Nothing {
            get {
                return ResourceManager.GetString("Item_Nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to download the version {0} ?.
        /// </summary>
        internal static string NewVersion_Message {
            get {
                return ResourceManager.GetString("NewVersion_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version {0} is now available on Github !.
        /// </summary>
        internal static string NewVersion_MessageLabel {
            get {
                return ResourceManager.GetString("NewVersion_MessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available.
        /// </summary>
        internal static string NewVersion_Title {
            get {
                return ResourceManager.GetString("NewVersion_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Frame: {0}.
        /// </summary>
        internal static string PokeFinder_CurrentFrame {
            get {
                return ResourceManager.GetString("PokeFinder_CurrentFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokemon with filters found..
        /// </summary>
        internal static string Pokemon_Found {
            get {
                return ResourceManager.GetString("Pokemon_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokemon with filters found. Catch it manually..
        /// </summary>
        internal static string Pokemon_FoundCatch {
            get {
                return ResourceManager.GetString("Pokemon_FoundCatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokemon is not valid.
        /// </summary>
        internal static string Pokemon_NotValid {
            get {
                return ResourceManager.GetString("Pokemon_NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROM {0} loaded.
        /// </summary>
        internal static string Rom_Loaded {
            get {
                return ResourceManager.GetString("Rom_Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ROM loaded.
        /// </summary>
        internal static string Rom_NotLoaded {
            get {
                return ResourceManager.GetString("Rom_NotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ROM is not supported.
        /// </summary>
        internal static string Rom_NotSupported {
            get {
                return ResourceManager.GetString("Rom_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string Settings_Pause {
            get {
                return ResourceManager.GetString("Settings_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        internal static string Settings_Sound {
            get {
                return ResourceManager.GetString("Settings_Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string Settings_Speed {
            get {
                return ResourceManager.GetString("Settings_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start this bot while you are on the map.
        /// </summary>
        internal static string SpinBot_StartOnlyMap {
            get {
                return ResourceManager.GetString("SpinBot_StartOnlyMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t spin the player, next move is unknown.
        /// </summary>
        internal static string SpinBot_UnknowNextMove {
            get {
                return ResourceManager.GetString("SpinBot_UnknowNextMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No symbols found for this game..
        /// </summary>
        internal static string Symbols_Empty {
            get {
                return ResourceManager.GetString("Symbols_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot.
        /// </summary>
        internal static string Tab_BotPanel {
            get {
                return ResourceManager.GetString("Tab_BotPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot Stats.
        /// </summary>
        internal static string Tab_EncounterStats {
            get {
                return ResourceManager.GetString("Tab_EncounterStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        internal static string Tab_LogsPanel {
            get {
                return ResourceManager.GetString("Tab_LogsPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Tab_SettingsPanel {
            get {
                return ResourceManager.GetString("Tab_SettingsPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opponent.
        /// </summary>
        internal static string Tab_ViewerOpponentName {
            get {
                return ResourceManager.GetString("Tab_ViewerOpponentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party.
        /// </summary>
        internal static string Tab_ViewerPartyName {
            get {
                return ResourceManager.GetString("Tab_ViewerPartyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s better to have some delay between each actions to avoid the bot to freeze while doing input. 0.1 is recommanded..
        /// </summary>
        internal static string Tooltip_Delay {
            get {
                return ResourceManager.GetString("Tooltip_Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ability: {0}.
        /// </summary>
        internal static string Viewer_Ability {
            get {
                return ResourceManager.GetString("Viewer_Ability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack: {0}.
        /// </summary>
        internal static string Viewer_Attack {
            get {
                return ResourceManager.GetString("Viewer_Attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defense: {0}.
        /// </summary>
        internal static string Viewer_Defense {
            get {
                return ResourceManager.GetString("Viewer_Defense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender: {0}.
        /// </summary>
        internal static string Viewer_Gender {
            get {
                return ResourceManager.GetString("Viewer_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden Power Damage: {0}.
        /// </summary>
        internal static string Viewer_HiddenPowerDamage {
            get {
                return ResourceManager.GetString("Viewer_HiddenPowerDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden Power: {0}.
        /// </summary>
        internal static string Viewer_HiddenPowerType {
            get {
                return ResourceManager.GetString("Viewer_HiddenPowerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HP: {0}.
        /// </summary>
        internal static string Viewer_HP {
            get {
                return ResourceManager.GetString("Viewer_HP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item: {0}.
        /// </summary>
        internal static string Viewer_Item {
            get {
                return ResourceManager.GetString("Viewer_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}/{2}).
        /// </summary>
        internal static string Viewer_Move {
            get {
                return ResourceManager.GetString("Viewer_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nature: {0}.
        /// </summary>
        internal static string Viewer_Nature {
            get {
                return ResourceManager.GetString("Viewer_Nature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /.
        /// </summary>
        internal static string Viewer_NoMove {
            get {
                return ResourceManager.GetString("Viewer_NoMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not shiny.
        /// </summary>
        internal static string Viewer_NotShiny {
            get {
                return ResourceManager.GetString("Viewer_NotShiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PID: {0}.
        /// </summary>
        internal static string Viewer_PID {
            get {
                return ResourceManager.GetString("Viewer_PID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shiny.
        /// </summary>
        internal static string Viewer_Shiny {
            get {
                return ResourceManager.GetString("Viewer_Shiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sp. Attack: {0}.
        /// </summary>
        internal static string Viewer_SpAttack {
            get {
                return ResourceManager.GetString("Viewer_SpAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sp. Defense: {0}.
        /// </summary>
        internal static string Viewer_SpDefense {
            get {
                return ResourceManager.GetString("Viewer_SpDefense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed: {0}.
        /// </summary>
        internal static string Viewer_Speed {
            get {
                return ResourceManager.GetString("Viewer_Speed", resourceCulture);
            }
        }
    }
}
