# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0
    - run: echo $GITHUB_WORKSPACE
    - name: Restore Packages
      run: nuget restore Pokebot.sln
    - name: Build Solution
      run: |
        msbuild.exe Pokebot.sln /p:platform="Any CPU" /p:configuration="Release"
  publish:
    needs: build
    runs-on: windows-latest
    steps:
    - uses: actions/upload-artifact@master
      with:
       name: Pokebot
       path: BizHawk\ExternalTools\Pokebot.dll
    - uses: actions/upload-artifact@master
      with:
       name: Pokebot2
       path: src\bin\Release\net48\Pokebot.dll
