# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0
    - name: Restore Packages
      run: nuget restore Pokebot.sln
    - name: Build Solution
      run: |
        msbuild.exe Pokebot.sln /p:platform="Any CPU" /p:configuration="Release"
    - name: Get version
      uses: kzrnm/get-net-sdk-project-versions-action@v1
      id: get-version
      with:
        proj-path: src/Pokebot.csproj
    - run: echo "${{steps.get-version.outputs.version}}"
    - run: echo "${{steps.get-version.outputs.version-prefix}}" 
    - run: echo "${{steps.get-version.outputs.version-suffix}}" 
    - run: echo "${{steps.get-version.outputs.package-version}}" 
    - run: echo "${{steps.get-version.outputs.assembly-version}}" 
    - run: echo "${{steps.get-version.outputs.file-version}}" 
    - run: echo "${{steps.get-version.outputs.informational-version}}" 
